#!/bin/bash
# Script para descargar dataset de alcohol-consumption y copiarlo a HDFS: cargar_drinks.sh
/*Paso a paso para ejecutar el script cargar_drinks.sh:
	1) Guardar el script en el sistema C:/Users/tuUsuario
	2) Abrir Git Bash
	3) Copiar el script al contenedor: docker cp cargar_drinks.sh edvai_hadoop:/home/hadoop/
	4) Ejecutar el contenedor: docker exec -it edvai_hadoop bash
	5) Cambiar al user hadoop: su hadoop
Ejecutar el script<img width="787" height="158" alt="image" src="https://github.com/user-attachments/assets/8f303f55-93a4-4f14-8e43-166e5edf3a11" />*/

# Descargar archivo
wget -P /home/hadoop/landing \
"https://raw.githubusercontent.com/fivethirtyeight/data/master/alcohol-consumption/drinks.csv"

if [ $? -ne 0 ]; then
  echo "❌ Error al descargar el archivo con wget."
  exit 1
fi

# Subir archivo a HDFS
hdfs dfs -mkdir -p /ingest
hdfs dfs -put -f /home/hadoop/landing/drinks.csv /ingest

if [ $? -eq 0 ]; then
  echo "✅ Archivo copiado exitosamente a HDFS: /ingest/drinks.csv"
else
  echo "❌ Error al copiar el archivo a HDFS."
  exit 1
fi
